Mention the need for zones with NVIDIA Tesla K80 Accelerators for the default GCP configuration
kubeflow/website pull request #1988
Opened 2020-06-09 20:17 UTC by yashjakhotiya

Solves #1987

2020-06-15 15:43 UTC, janeman98 commented
@abhi-g 
Can you (or find someone in your company to) review this PR? Thanks!

2020-07-22 00:32 UTC, joeliedtke commented
/assign

2020-07-22 00:32 UTC, joeliedtke commented
preview: https://deploy-preview-1988--competent-brattain-de2d6d.netlify.app/docs/gke/deploy/deploy-cli/

2020-07-22 00:34 UTC, joeliedtke commented
@Bobgy, do you know if the following manifest requires NVIDIA K80 GPUs?

https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.2.yaml

2020-07-23 02:56 UTC, Bobgy commented
Yes, that's true.
Thanks for updating the doc!
/lgtm
/approve

2020-07-28 00:07 UTC, joeliedtke commented
/approve

2020-09-02 08:12 UTC, Bobgy commented
@yashjakhotiya Can you please resolve the merge conflict?
Thanks!

2020-11-26 00:41 UTC, 8bitmp3 commented
Hi @yashjakhotiya I hope all is good! Please resolve the merge issue (cc @Bobgy @joeliedtke @RFMVasconcelos). This PR has gone a bit stale

2020-11-26 04:16 UTC, Bobgy commented
I've helped resolve merge conflicts and update some content.
/assign @8bitmp3 
do you want to review?

2020-12-12 00:02 UTC, 8bitmp3 requested changes
Hey @yashjakhotiya Hope you didn't have to wait for too long, I've added a few suggestions. They're mainly about formatting code blocks.

Can you please lint the entire `deploy-cli.md` and add `shell` next to three backticks in the beginning of code blocks to improve formatting in Markdown on the site?

For example:

```
    ```shell
    gcloud ....
    ```
```

Thank you


cc @Bobgy

2020-12-12 00:02 UTC, 8bitmp3 commented on content/en/docs/gke/deploy/deploy-cli.md
> +* **${KF_DIR}** - The full path to your Kubeflow application directory.
```suggestion
* **${KF_DIR}**: The full path to your Kubeflow application directory.
```

2020-12-12 06:39 UTC, Bobgy commented
@8bitmp3 I don't think @yashjakhotiya has responded since creating the PR.
Let's get this in, because it's already an improvement
/lgtm
/approve

2020-12-12 06:41 UTC, merged