WIP: Update "Kubeflow on Linux" getting started page
kubeflow/website pull request #2144
Opened 2020-08-19 18:25 UTC by RFMVasconcelos

### TODOs:

1. Removing / Updating `Kind ` installation as there are no docs - #2141
2. Restructuring content: the page looks quite confusing, event though there are only 3 ways to deploy:
> - Microk8s (download or with multipass)
> - MiniKF
> - MiniKube

### Page now:
![image](https://user-images.githubusercontent.com/27001378/90672713-72d35380-e24e-11ea-8802-1b209bea343b.png)

2020-08-24 07:24 UTC, alfsuse commented
@RFMVasconcelos we have https://www.kubeflow.org/docs/pipelines/installation/localcluster-deployment/ where we described how to install KF pipelines in Kind, I can create easily an equivalent page for the full KF installation using Kind and K3s. Let me know what do you think and I'll open a PR for this.

2020-09-14 09:20 UTC, RFMVasconcelos commented
Hi @alfsuse! Thank you for the clarification. Is this in your opinion a good description of Kind installation? (The current one?)

![image](https://user-images.githubusercontent.com/27001378/93067968-c715fb80-f673-11ea-986b-0c06091c8e5f.png)

Can you specify where the broken link should point now to?

2020-09-14 09:27 UTC, alfsuse commented
> Hi @alfsuse! Thank you for the clarification. Is this in your opinion a good description of Kind installation? (The current one?)
Yes absolutely!
> 
> ![image](https://user-images.githubusercontent.com/27001378/93067968-c715fb80-f673-11ea-986b-0c06091c8e5f.png)
> 
> Can you specify where the broken link should point now to?
I was thinking more at adding some extra sections to your "kubeflow on linux" section..with kind and k3s since the one I wrote before is just for KF pipelines.. let me know if I can help you with this :)

2020-10-22 20:33 UTC, 8bitmp3 commented
Hi @alfsuse @RFMVasconcelos Does this PR still need any work, given the recent updates?

2020-10-22 20:33 UTC, 8bitmp3 requested changes
PTAL (comment before)

2020-10-23 13:15 UTC, alfsuse commented
> Hi @alfsuse @RFMVasconcelos Does this PR still need any work, given the recent updates?
@8bitmp3 @RFMVasconcelos 

On K3ai we got now PyTorch-job, TF-job, Pipelines (we already a section for this), KFP DSK with Jupyter Notebooks and we are adding Katib today so I was wondering does it make sense to create a K3ai page/section and highlight it into this page? 
I can mark K3ai as [beta/alpha] since is less mature than microK8s and other solution but could be in the direction of making more modular the Kubeflow experience of installation and offer another community alternative.

Otherwise, IMO I think we may close and merge this PR.

2020-10-23 14:13 UTC, RFMVasconcelos commented
Hi @8bitmp3, I think that given the updates this PR is redundant.

Hi @alfsuse! 
Is the K3ai goal to be a deployment method for Kubeflow on Workstations? 
What is the ideal place for users to find it and know what to expect from it?

2020-10-23 14:18 UTC, RFMVasconcelos commented
@alfsuse Maybe I can close this PR and you can open up an issue/PR inquiring/suggesting where to locate k3ai?  WDYT?

2020-10-23 14:25 UTC, alfsuse commented
Yep good idea... I'll open a PR and mark it as WIP

2020-10-23 14:35 UTC, alfsuse commented
@RFMVasconcelos 
> Is the K3ai goal to be a deployment method for Kubeflow on Workstations?

Yes, and No, we make K3ai as a modular "lego" for AI where folks may cherry-picking the modules they like from Kubeflow and run them on their workstations/edge/laptops devices. The reason to not bring the full KF is due to the limitation many folks have when it comes to RAM/CPU/GPU's.
Nonetheless, we aim to support the full KF installation for compliance reason toward the actual way to install KF.

> What is the ideal place for users to find it and know what to expect from it?

Here's the problem I'm facing, if I look at what we support (https://docs.k3a.in) there would be various places where we could appear but to avoid confusion and redundancy in the documentation my idea was a "short" section under the workstation guide dedicated to K3ai as we have for MiniKF and MicroK8s plus some references to other specific sections (pipelines already exist, I was thinking to add Katib as well ).

I was thinking to report anyway this answer/thread as part of the new PR so the community may eventually comment on this... Also if there's interest I would be super happy to present at one of the next community meeting K3ai so KF folks may learn more about our approach.

2020-10-23 16:40 UTC, RFMVasconcelos commented
This looks quite interesting! 

If you want to

2020-10-23 16:42 UTC, RFMVasconcelos commented
I'll close this PR then.

/close

2020-10-23 16:42 UTC, closed without merging