Link to more info about the MANAGED_PROJECT
kubeflow/website pull request #2153
Opened 2020-08-25 11:37 UTC by mnmami

It was not clear what to put in MANAGED_PROJECT, especially that opening ./instance/managed-project/iam.yaml put the MANAGED_PROJECT as the namespace. More description here is needed.

2020-08-25 11:39 UTC, mnmami commented
@googlebot I signed it!

2020-08-27 19:57 UTC, 8bitmp3 requested changes
Hey @mnmami Thanks for the short PR!

My only suggestion is to break the sentence into two simpler ones, while shortening the second added thing and keeping the main gist.

```diff
- Consequently
+ Consequently,
you need to grant this GCP service account sufficient privileges to create the desired
- resources in one or more projects (called managed projects, read [more]
- (https://github.com/kubeflow/gcp-blueprints/tree/master/management/instance/managed-project)). 
+ resources in one or more projects. These are called 
+ [managed projects](https://github.com/kubeflow/gcp-blueprints/tree/master/management/instance/managed-project)).
```

What do you think?

cc @Bobgy (he knows way more about deployments than 8bitmp3). I think @Bobgy is also working on something within `management-setup.md`—I've just reviewed one of the PRs.

2020-08-27 19:57 UTC, 8bitmp3 commented on content/en/docs/gke/deploy/management-setup.md
> +resources in one or more projects (called managed projects, read [more](https://github.com/kubeflow/gcp-blueprints/tree/master/management/instance/managed-project)).
```diff
- Consequently
+ Consequently,
you need to grant this GCP service account sufficient privileges to create the desired
- resources in one or more projects (called managed projects, read [more]
- (https://github.com/kubeflow/gcp-blueprints/tree/master/management/instance/managed-project)). 
+ resources in one or more projects. These are called 
+ [managed projects](https://github.com/kubeflow/gcp-blueprints/tree/master/management/instance/managed-project)).
```

2020-08-28 03:35 UTC, Bobgy commented on content/en/docs/gke/deploy/management-setup.md
> +resources in one or more projects (called managed projects, read [more](https://github.com/kubeflow/gcp-blueprints/tree/master/management/instance/managed-project)).
Thanks @mnmami! It's probably better directly include that paragraph here.

2020-09-28 21:43 UTC, joeliedtke commented
/ok-to-test

2020-09-28 21:46 UTC, joeliedtke commented
Preview: https://deploy-preview-2153--competent-brattain-de2d6d.netlify.app/docs/gke/deploy/management-setup/

2020-09-29 10:23 UTC, Bobgy commented
Can you please fix the merge conflict?
/lgtm
otherwise

2020-09-29 11:08 UTC, Bobgy commented
@mnmami Thank you for your contribution!
/lgtm
/approve

2020-09-29 11:09 UTC, merged