[docs:] Fix missing port-foward URL
kubeflow/website pull request #2292
Opened 2020-10-19 06:56 UTC by alfsuse

Apparently, in the last rework, we deleted the port-forward section that helps folks to be able to use the pipelines UI.
/assign @8bitmp3 /cherry-picking

2020-10-22 20:44 UTC, 8bitmp3 requested changes
Thanks! Suggestions @alfsuse :

- Add a space/separator, before step 2
- Use [code font](https://developers.google.com/style/code-in-text) for URLs (i.e. backticks)
- Some refactoring

```suggestion

2. Verify that the Kubeflow Pipelines UI is accessible by port-forwarding:

    ```shell
    kubectl port-forward -n kubeflow svc/ml-pipeline-ui 8080:80
    ```

    Then, open the Kubeflow Pipelines UI at `http://localhost:8080/` or - if you are
    using kind or K3s within a virtual machine - `http://{YOUR_VM_IP_ADDRESS}:8080/`
    
    Note that K3ai will automatically print the URL for the web UI at the end of
    the installation process.
```

LMKWYT

2020-10-22 20:44 UTC, 8bitmp3 commented on content/en/docs/pipelines/installation/localcluster-deployment.md
> +Please note that K3ai will automatically print the right UI URL at the end of the installation process.
Thanks! Suggestions @alfsuse :

- Add a space/separator, before step 2
- Use [code font](https://developers.google.com/style/code-in-text) for URLs (i.e. backticks)
- Some refactoring

```suggestion

2. Verify that the Kubeflow Pipelines UI is accessible by port-forwarding:

    ```shell
    kubectl port-forward -n kubeflow svc/ml-pipeline-ui 8080:80
    ```

    Then, open the Kubeflow Pipelines UI at `http://localhost:8080/` or - if you are
    using kind or K3s within a virtual machine - `http://{YOUR_VM_IP_ADDRESS}:8080/`
    
    Note that K3ai will automatically print the URL for the web UI at the end of
    the installation process.
```

LMKWYT

2020-10-23 19:55 UTC, 8bitmp3 commented
/lgtm

Thanks @alfsuse 🍾 

/assign @Bobgy @IronPan @neuromage @Ark-kun @numerology

PTAL and approve if all is 👍 Thanks

2020-10-26 00:01 UTC, Bobgy commented
/approve
Thanks

2020-10-26 00:05 UTC, merged