Update getting-started-minikf.md
kubeflow/website pull request #2299
Opened 2020-10-21 01:21 UTC by jbottum

2020-10-22 20:31 UTC, 8bitmp3 requested changes
@jbottum Hi, a few suggestions for this PR:

- Improve the title for better discoverability. Also, new users should be able to understand what this guide does quicker, hopefully, if we tweak it a little.

cc @alfsuse 

```diff
- title = "MiniKF"		
+ title = "Deploy Kubeflow locally with MiniKF"
```

Also, maybe we should merge lines 17 and 19 - then both sentences don't have to start with "MiniKF.... MiniKF..."

```
MiniKF is a production-ready, full-fledged, local Kubeflow deployment that
installs in minutes. It is a fast and easy way to get started with Kubeflow. With just a
...
```

2020-10-22 20:31 UTC, 8bitmp3 commented on content/en/docs/started/workstation/getting-started-minikf.md
>  MiniKF is a fast and easy way to get started with Kubeflow. With just a
Suggestion: 

- Merge these, then both sentences don't have to start with "MiniKF.... MiniKF.."

```suggestion
MiniKF is a production-ready, full-fledged, local Kubeflow deployment that
installs in minutes. It is a fast and easy way to get started with Kubeflow. With just a
```

2020-10-23 07:39 UTC, alfsuse commented on content/en/docs/started/workstation/getting-started-minikf.md
> -+++
Hi, @jbottum also you have to put back this line. the '+++' is needed for the title and without that the deployment will fail.

2020-11-02 22:50 UTC, 8bitmp3 commented
Hi @jbottum let us know what you think and if you have an update. @alfsuse and I are here to help. Cheers! 
cc @RFMVasconcelos

2020-11-02 23:36 UTC, jbottum commented
Hi @8bitmp3 , thanks for the improvements.   The MiniKF PM asked me to close this and will open another issue in a few days.

2020-11-02 23:36 UTC, closed without merging

2020-11-02 23:37 UTC, jbottum commented
Let's close this unmerged.   the MiniKF PM will open another issue for the update in a few days.   thanks for your help.