Update GCP doc - setting a custom domain
kubeflow/website pull request #2311
Opened 2020-10-23 13:57 UTC by BAlmeidaS

Changing the section *Using Your Own Domain* to be compliant with Kubeflow 1.1 version using kpt.

2020-10-23 19:49 UTC, 8bitmp3 requested changes
Hey @BAlmeidaS Thanks for the update.

A few suggestions: 

- "kptfile" -> "the Kptfile" (reference: https://googlecontainertools.github.io/kpt/search/?q=kptfile)

```
1. Remove the substitution `hostname` in the Kptfile.
...
1. Create a new setter `hostname` in kptfile.
```

Also, can you please add spaces before a couple of code blocks? (Better formatting, as per the Google style guide).

LMKWYT! Assigning the GCP team

/assign @Bobgy @joeliedtke @rmgogogo

cc @RFMVasconcelos (regarding outdated docs)

2020-10-23 19:49 UTC, 8bitmp3 commented on content/en/docs/gke/custom-domain.md
> +1. Remove the substitution `hostname` in kptfile.
Suggestion: 

- "kptfile" -> "the Kptfile" (reference: https://googlecontainertools.github.io/kpt/search/?q=kptfile)

```suggestion
1. Remove the substitution `hostname` in the Kptfile.
```

2020-10-23 19:49 UTC, 8bitmp3 commented on content/en/docs/gke/custom-domain.md
> +1. Create a new setter `hostname` in kptfile.
```suggestion
1. Create a new setter `hostname` in the Kptfile.
```

2020-10-23 19:49 UTC, 8bitmp3 commented on content/en/docs/gke/custom-domain.md
>      ```
Suggestion:

- Add space before the code block

```suggestion

    ```
```

2020-10-23 19:49 UTC, 8bitmp3 commented on content/en/docs/gke/custom-domain.md
>  1. Check Ingress to verify that your domain was properly configured.
Suggestion:

- Add space before the code block after the instruction step

```suggestion
1. Check Ingress to verify that your domain was properly configured.

```

2020-10-23 20:31 UTC, BAlmeidaS commented
I applied your suggestions @8bitmp3. Tks for your review

2020-10-26 06:48 UTC, Bobgy commented
/assign @jlewi 
Can you help review?

Looks good for me, but I don't have much knowledge on how to configure custom domain name.
/approve
/hold

2020-10-26 06:48 UTC, Bobgy commented
/ok-to-test

2020-11-02 22:45 UTC, 8bitmp3 commented
gently ping @jlewi

2020-11-03 00:33 UTC, jlewi commented
/lgtm
/approve

Thanks

2020-11-03 00:33 UTC, jlewi commented
/hold cancel

2020-11-03 00:36 UTC, merged