[WIP] Add Katib metric strategies info
kubeflow/website pull request #2316
Opened 2020-10-27 02:01 UTC by andreyvelich

Fixes: https://github.com/kubeflow/katib/issues/1310.
Blocked by: https://github.com/kubeflow/website/pull/2312.

I added doc about `metricStrategies` in Objective section.

/assign @johnugeorge @gaocegege 

/cc @8bitmp3

2020-11-11 13:29 UTC, andreyvelich commented
This PR is ready.
/cc @gaocegege @8bitmp3 @johnugeorge

2020-11-11 13:42 UTC, 8bitmp3 commented on content/en/docs/components/katib/experiment.md
> +  in experiment's `.status.currentOptimalTrial.parameterAssignments`.
```suggestion
  in the experiment's `.status.currentOptimalTrial.parameterAssignments`.
```

2020-11-11 13:44 UTC, 8bitmp3 commented on content/en/docs/components/katib/experiment.md
> +  You are able to change the default mechanism. For that, define
```suggestion
  To change the default settings, define
```

2020-11-11 13:44 UTC, 8bitmp3 commented on content/en/docs/components/katib/experiment.md
> +  For example, if you set the below parameters in your experiment:
```suggestion
  For example, you can set the parameters in your experiment as follows:
```

2020-11-11 13:45 UTC, 8bitmp3 commented on content/en/docs/components/katib/experiment.md
> +  Katib controller is searching for the best maximum from the all latest
```suggestion
  where the Katib controller is searching for the best maximum from the all latest
```

2020-11-11 13:45 UTC, 8bitmp3 requested changes
PTAL 👍

2020-11-11 15:52 UTC, andreyvelich reviewed
Thank you for the review @8bitmp3.
I made changes.

2020-11-13 13:56 UTC, gaocegege reviewed
LGTM :+1:
/lgtm

2020-11-13 14:00 UTC, merged