Add Notebook WG leads to OWNERS
kubeflow/website pull request #2319
Opened 2020-10-28 02:54 UTC by thesuperzapper

This adds the Notebook Working Group Leads as OWNERS for the Notebook docs.

2020-10-28 02:55 UTC, thesuperzapper commented
@RFMVasconcelos can you please review?

2020-10-28 11:54 UTC, RFMVasconcelos commented
Sure! 

/assign @RFMVasconcelos

2020-10-28 13:55 UTC, RFMVasconcelos requested changes
Thank you for this @thesuperzapper! 

For reference, approvers have all the permissions of reviewers + the fact that they can approve docs. I don't think it makes sense to repeat names on both (no other OWNERS file has this pattern, from my knowledge).

It might be best to have only a couple of people who can approve, so these are more accountable, and people know who to reach out to, but I leave that choice to you.

2020-10-28 23:43 UTC, 8bitmp3 requested changes
Thanks @thesuperzapper. Take a look at what @RFMVasconcelos suggested. 

You can also add meme - @8bitmp3 - as a reviewer (I have experience working as well as editing notebooks, TensorFlow and PyTorch in accordance with common style guides by Google/TF and Microsoft).

Cheers!

2020-10-29 23:21 UTC, thesuperzapper commented
@8bitmp3 there is no need to add you as a reviewer, as you are already a reviewer in the root OWNERS file

2020-10-29 23:22 UTC, thesuperzapper commented
@RFMVasconcelos I have updated the PR to only assign approvers

2020-10-30 10:01 UTC, RFMVasconcelos commented
Great @thesuperzapper !

/lgtm

2020-10-30 10:38 UTC, RFMVasconcelos commented
/approve

2020-10-30 10:39 UTC, RFMVasconcelos commented
/assign @Bobgy

2020-11-03 22:51 UTC, thesuperzapper commented
@Bobgy can you please LGTM this?

2020-11-04 07:12 UTC, Bobgy commented
/lgtm
/approve
Sure, thank you for starting taking care of the docs!

2020-11-04 07:16 UTC, merged