cherrypick of "KFP - Updated the documentation regarding metrics #2171"
kubeflow/website pull request #2363
Opened 2020-11-23 01:39 UTC by Bobgy

/assign @Ark-kun @8bitmp3 

website now shows 1.1-branch by default, so let's cherry pick

2020-11-23 01:40 UTC, Bobgy commented
Forced cla because @Ark-kun is a Googler

2020-11-23 13:11 UTC, 8bitmp3 commented on content/en/docs/pipelines/sdk/pipelines-metrics.md
> +Otherwise the Kubeflow Pipelines UI will
```suggestion
Otherwise, the Kubeflow Pipelines UI will
```

2020-11-23 13:13 UTC, 8bitmp3 commented on content/en/docs/pipelines/sdk/pipelines-metrics.md
> +An example Lightweight python component that outputs metrics dictionary by writing it to an output file:
```suggestion
Below is an example of a lightweight Python component that outputs metrics dictionary by writing it to an output file:
```

2020-11-23 13:13 UTC, 8bitmp3 commented on content/en/docs/pipelines/sdk/pipelines-metrics.md
> +An example script-based `component.yaml` component:
```suggestion
And this is an example of a script-based `component.yaml` component:
```

2020-11-23 13:14 UTC, 8bitmp3 requested changes
thanks @Bobgy PTAL

2020-11-24 07:57 UTC, Bobgy commented
Hi @8bitmp3! Thank you for the detailed review, but this is a cherry pick PR, so we shouldn't update anything here.

Do you want to submit a PR with your suggestions to master branch?

2020-11-25 20:57 UTC, Ark-kun commented
/lgtm

2020-11-25 21:00 UTC, merged