WIP. fix(docs): updated the quickstart for kubeflow pipelines. Fixes 4617 in (kubeflow/pipelines)
kubeflow/website pull request #2512
Opened 2021-02-20 16:33 UTC by NikeNano

Relates to: https://github.com/kubeflow/pipelines/issues/4617

2021-03-02 12:11 UTC, JohanWork commented on content/en/docs/pipelines/pipelines-quickstart.md
> +Once you have deployed kubeflow pipelines make sure you can access the UI, this step depends on the method of deployment.
```suggestion
Once you have deployed kubeflow pipelines make sure you can access the UI, how to do it varied depending on the deployment method. 
```

2021-03-02 12:13 UTC, JohanWork commented on content/en/docs/pipelines/pipelines-quickstart.md
> +You can find [the source code for the data passing in python components sample](https://github.com/kubeflow/pipelines/tree/master/samples/tutorials/Data%20passing%20in%20python%20components)
```suggestion
You can find [the source code for the python components](https://github.com/kubeflow/pipelines/tree/master/samples/tutorials/Data%20passing%20in%20python%20components)
```

2021-03-04 19:17 UTC, NikeNano commented
/assign @bobgy

2021-03-09 16:40 UTC, Bobgy commented
Thank you so much! This looks great!

/LGTM
/Assign @joeliedtke 
In case you want to review

2021-03-12 02:20 UTC, Bobgy commented
Note, the rendered page can be viewed at https://deploy-preview-2512--competent-brattain-de2d6d.netlify.app/docs/components/pipelines/pipelines-quickstart/

2021-03-14 19:55 UTC, joeliedtke requested changes
Thanks for updating this doc, I've added a few suggestions.

2021-03-14 19:55 UTC, joeliedtke commented on content/en/docs/components/pipelines/pipelines-quickstart.md
> +Once you have deployed Kubeflow Pipelines make sure you can access the UI, this step depends on the method of deployment.
Suggested revision (grammar, clarity): 

Once you have deployed Kubeflow Pipelines, make sure you can access the UI. The steps to access the UI vary based on the method you used to deploy Kubeflow Pipelines.

2021-03-14 19:55 UTC, joeliedtke commented on content/en/docs/components/pipelines/pipelines-quickstart.md
> +There are several options to [deploy Kubeflow Pipelines](/docs/components/pipelines/installation/), follow the option that best suits your needs. If you are uncertain and just want to try out kubeflo
Nit: I would recommend linking directly to the installation options page

[deploy Kubeflow Pipelines](/docs/components/pipelines/installation/overview/)

2021-03-14 19:55 UTC, joeliedtke commented on content/en/docs/components/pipelines/pipelines-quickstart.md
> +Kubeflow Pipelines offers a few default samples that you can use to try out
Remove "default"

2021-03-14 19:55 UTC, joeliedtke commented on content/en/docs/components/pipelines/pipelines-quickstart.md
> +You can find the source code for the **Data passing in python components** tutorial
It's better to use link text that describes the content that we are linking to. Suggested revision

You can find the [source code for the **Data passing in python components** tutorial](https://github.com/kubeflow/pipelines/tree/master/samples/tutorials/Data%20passing%20in%20python%20components) in the Kubeflow Pipelines repo.

2021-03-14 19:55 UTC, joeliedtke commented on content/en/docs/components/pipelines/pipelines-quickstart.md
> +You can find the source code for the **XGBoost - Iterative model training** demo in the
Suggested revision:

You can find the [source code for the **XGBoost - Iterative model training** demo](https://github.com/kubeflow/pipelines/tree/master/samples/core/xgboost_training_cm) in the 
Kubeflow Pipelines repo.

2021-03-14 20:40 UTC, NikeNano commented
> Thanks for updating this doc, I've added a few suggestions.

Thanks for the feedback, update with your suggestions @joeliedtke

2021-03-14 22:20 UTC, joeliedtke commented
/lgtm
/approve

Thanks for updating this page, @NikeNano!

2021-03-14 22:20 UTC, merged