AWS Docs: update & add debug tools
kubeflow/website pull request #2958
Opened 2021-09-18 17:54 UTC by bankbiz

- Replace old snapshots make it more present as AWS dashboard change so much including `route53-a-record-auth.png` and `route53-a-record-platform.png`. Please update to production image folder.
- Add some debug command and link to exist common troubleshooting.
- Add and fix some missing step.

2021-09-18 18:32 UTC, bankbiz commented
@googlebot I signed it!

2021-09-21 17:57 UTC, AlexandreBrown approved these changes

2021-09-22 02:27 UTC, bankbiz commented
/assign @PatrickXYS

2021-11-18 01:35 UTC, Jeffwan commented
/cc @goswamig

2021-11-18 01:35 UTC, Jeffwan commented
@goswamig Did you add yourself as approver on AWS docs?

2021-11-19 22:04 UTC, goswamig commented
Not yet let me add myself.

2021-11-19 22:26 UTC, surajkota requested changes
Thanks for the enhancements to the docs!

Few comments

2021-11-19 22:26 UTC, surajkota commented on content/en/docs/distributions/aws/aws-e2e.md
>  When it's created, it will return the `Alias target` cloudfront address for which you need to create a `A Record` `auth.platform.domain.com` in the hosted zone.
Can add a text here saying `use the alias button`.

2021-11-19 22:26 UTC, surajkota commented on content/en/docs/distributions/aws/aws-e2e.md
> +<img src="https://graffity-public-assets.s3.ap-southeast-1.amazonaws.com/route53-a-record-auth.png"
it will be good to have the images in the repo for maintenance purposes

2021-11-19 22:26 UTC, surajkota commented on content/en/docs/distributions/aws/aws-e2e.md
> +* The ARN (`certArn`) of the certificate from the Certificate Manager of your region, 'eu-west-1' in this case.
your region -> of the deployment region(i.e. cluster region)

2021-11-19 22:26 UTC, surajkota commented on content/en/docs/distributions/aws/aws-e2e.md
> +* `kubeflow.platform.domain.com`
there is already an entry for `*.platform.domain.com`. This shouldn't be needed

2021-11-19 22:26 UTC, surajkota commented on content/en/docs/distributions/aws/aws-e2e.md
> +<img src="https://graffity-public-assets.s3.ap-southeast-1.amazonaws.com/route53-a-record-platform.png"
same comment for the image

2021-11-20 03:41 UTC, AlexandreBrown commented on content/en/docs/distributions/aws/aws-e2e.md
> +That shouldn't take a long time. There shouldn't by any errors, and when ready you can validate that you can see the kubeflow namespace by following command:
Should the text be "There shouldn't **be** any errors" instead ?

2021-11-20 03:42 UTC, AlexandreBrown commented on content/en/docs/distributions/aws/aws-e2e.md
> +That shouldn't take a long time. There shouldn't by any errors, and when ready you can validate that you can see the kubeflow namespace by following command:
Maybe "namespace by **using the** following command:

2021-11-20 03:44 UTC, AlexandreBrown commented on content/en/docs/distributions/aws/aws-e2e.md
> +That shouldn't take a long time. There shouldn't by any errors, and when ready you can validate that you can see the kubeflow namespace by following command:
Maybe the last part could be "namespace by using the following command:"

What do you think?

2021-11-24 06:17 UTC, bankbiz commented
Sure! All requests are updated.

2022-02-05 15:09 UTC, Arhell reviewed
/ok-to-test

2022-03-03 18:39 UTC, surajkota commented
Hi @bankbiz Thank you for the contribution and insights. We have updated the documentation since this PR and also taken these suggestions into account. Please find the updated documentation on the [website](https://www.kubeflow.org/docs/distributions/aws/deploy/install-kubeflow/#deployment-options) and https://github.com/awslabs/kubeflow-manifests/tree/v1.3-branch/distributions/aws/examples/cognito#deploying-kubeflow-with-aws-cognito-as-idp and feel free to open a PR if further changes are needed.

ref: #3169 

/close

2022-03-03 18:39 UTC, closed without merging