Fix broken link
kubeflow/website pull request #3098
Opened 2021-12-14 15:44 UTC by shannonbradshaw

Going to push what I think is a fix. Though I'm a little confused, because this looks like it might be the result of a bug in markdown parsing.

2021-12-14 15:48 UTC, shannonbradshaw commented
Fixed. There was space in between the anchor [] and url ().

2021-12-15 00:34 UTC, Arhell reviewed
/assign @Bobgy

2021-12-16 02:56 UTC, thesuperzapper requested changes

2021-12-16 02:56 UTC, thesuperzapper commented on content/en/docs/distributions/openshift/install-kubeflow.md
> +1. Download the example "kfdef" for Kubeflow 1.3 on Openshift from [kubeflow/manifests/distributions/kfdef](https://raw.githubusercontent.com/opendatahub-io/manifests/v1.3-branch/distributions/kfdef/
I think its a bit confusing to link directly to the raw YAML (it removes the context of the repo).

I think its easier to understand if the link is:
```
https://github.com/kubeflow/manifests/blob/v1.3-branch/distributions/kfdef/kfctl_openshift_v1.3.0.yaml
```

2022-04-27 16:46 UTC, closed without merging