Minimized AWS Docs for Kubeflow 1.3.1
kubeflow/website pull request #3169
Opened 2022-03-02 23:09 UTC by judyheflin

This is a PR for the minimized documentation for Kubeflow on AWS. We are still in the process of migrating the docs over to our own site, and in the meantime need these minimized docs added. 

Resolves #3166

2022-03-02 23:26 UTC, surajkota commented
/ok-to-test

2022-03-02 23:28 UTC, akartsky approved these changes

2022-03-03 00:07 UTC, surajkota requested changes
Awesome Work on this! Left a few comments

2022-03-03 00:07 UTC, surajkota commented on content/en/docs/distributions/aws/troubleshooting-aws.md
> +You may experience issues due to version incompatibility. Before diving into more specific issues, check to make sure that you have the correct [prerequisites](https://github.com/awslabs/kubeflow-man
this is not making sense. surakota@ check with kartik

2022-03-03 00:07 UTC, surajkota commented on content/en/docs/distributions/aws/component-guides/pipeline.md
> +If you want to set up application load balancing (ALB) with Dex, see [Connect to Your Kubeflow Cluster](https://github.com/awslabs/kubeflow-manifests/tree/v1.3-branch/distributions/aws/examples/vanil
If you want to set up application load balancing (ALB) with Dex, see [Exposing Kubeflow over Load Balancer](https://github.com/awslabs/kubeflow-manifests/tree/v1.3-branch/distributions/aws/examples/vanilla#exposing-kubeflow-over-load-balancer) and use the ALB address as the Kubeflow Endpoint.

2022-03-03 00:32 UTC, surajkota commented
/retest cla/google

2022-03-03 00:53 UTC, surajkota commented
/approve
/lgtm

2022-03-03 00:54 UTC, merged