sdk: update local execution limitations
kubeflow/website pull request #3736
Opened 2024-05-17 22:34 UTC by connor-mccarthy

2024-05-17 22:39 UTC, connor-mccarthy commented
/assign @chensun

2024-05-17 22:50 UTC, sen-sam commented on content/en/docs/components/pipelines/v2/local-execution.md
> +- Local execution does not feature authentication mechanisms. If your component interacts with cloud resources or takes other privileged action, your pipeline is better-suited for testing in the clou
Nit (provided my edits preserve the implications of the statement): Local execution doesn't support authentication mechanisms. If your component interacts with cloud resources or requires other privileged actions, you need to test your pipeline in the cloud.

2024-05-17 22:51 UTC, sen-sam requested changes
Small nit. Mostly LGTM.

2024-05-17 22:56 UTC, sen-sam approved these changes
LGTM. Consider changing "you need to" to "you must" in a future PR.

2024-12-06 07:41 UTC, varodrig commented
@hbelmiro should we close this PR?

2024-12-06 12:26 UTC, hbelmiro commented
@varodrig This PR should target https://www.kubeflow.org/docs/components/pipelines/user-guides/core-functions/execute-kfp-pipelines-locally/ now. But, AFAIK, Connor is no longer contributing to Kubeflow.
Would you like to send a new PR with this change?

2024-12-14 04:48 UTC, varodrig commented
/close
content changed to another page. new PR submitted #3944 
requested by @hbelmiro

2024-12-14 04:48 UTC, closed without merging