Add Kubeflow 1.9 Release page
kubeflow/website pull request #3799
Opened 2024-07-08 21:53 UTC by rimolive

2024-07-08 21:53 UTC, rimolive commented
/hold

2024-07-22 17:04 UTC, rimolive commented
/unhold

2024-07-22 17:08 UTC, andreyvelich reviewed
Thank you @rimolive!
/lgtm
/assign @terrytangyuan @johnugeorge @jbottum @james-jwu

2024-07-23 05:09 UTC, thesuperzapper requested changes

2024-07-23 05:09 UTC, thesuperzapper commented on content/en/docs/releases/kubeflow-1.9.md
> +          <a href="https://www.youtube.com/watch?v=CUQT-YccpR8">Kubeflow 1.9 Release Overview</a>
This video is for Kubeflow 1.7.

2024-07-23 13:45 UTC, rimolive commented on content/en/docs/releases/kubeflow-1.9.md
> +          <a href="https://www.youtube.com/watch?v=CUQT-YccpR8">Kubeflow 1.9 Release Overview</a>
Changed the text to `To be published`.

2024-07-23 13:46 UTC, rimolive commented
@andreyvelich @james-jwu @johnugeorge @terrytangyuan @jbottum @thesuperzapper This PR is blocking the Kubeflow 1.9 blog post to be published. Please help with approving this asap.

2024-07-23 15:26 UTC, terrytangyuan approved these changes
/lgtm
/approve

2024-07-23 15:27 UTC, merged