Minor updates to website documentation
kubeflow/website pull request #3946
Opened 2024-12-14 23:27 UTC by varodrig

- Minor updates to Central Dashboard documentation

2024-12-28 09:45 UTC, Arhell reviewed
lgtm

2024-12-28 20:03 UTC, varodrig commented
/assign @thesuperzapper

2025-01-19 00:53 UTC, varodrig commented
@thesuperzapper any news on this PR?

2025-01-30 19:53 UTC, thesuperzapper requested changes
A few comments.

2025-01-30 19:53 UTC, thesuperzapper commented on content/en/docs/components/central-dash/profiles.md
> +A Kubeflow Profile is a [Kubernetes CRD](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#customresourcedefinitions) introduced by Kubeflow that wraps a Kubernete
It's not really correct to say it "solves access management" given the profile does not have any access management aspect, it literally just tells the controller to make a profile.

Access management is sadly done with the strange named RBAC resources, as described in this section.

```suggestion
A Kubeflow Profile is a [Kubernetes CRD](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#customresourcedefinitions) introduced by Kubeflow that wraps a Kubernetes [Namespace](https://kubernetes.io/docs/tasks/administer-cluster/namespaces-walkthrough/).
```

2025-01-30 19:53 UTC, thesuperzapper commented on content/en/docs/components/central-dash/profiles.md
> +## Explore Profile in the Central Dashboard
I think this is a better title:

```suggestion
## Profiles in the Central Dashboard
```

2025-01-30 19:53 UTC, thesuperzapper commented on content/en/docs/components/central-dash/profiles.md
> +* Istio AuthorizationPolicy
I don't this this helps a new user, as this section is trying to introduce the general concept of a Profile without overwhelming the reader:

```suggestion
```

2025-01-30 19:54 UTC, thesuperzapper commented on content/en/docs/components/central-dash/customize.md
> +The Kubeflow Central Dashboard is configured using a [Kubernetes ConfigMap](https://kubernetes.io/docs/concepts/configuration/configmap/).
```suggestion
The Kubeflow Central Dashboard is configured using a Kubernetes [ConfigMap](https://kubernetes.io/docs/concepts/configuration/configmap/).
```

2025-01-30 19:55 UTC, thesuperzapper commented on content/en/docs/components/central-dash/profiles.md
> +A Kubeflow Profile is a [Kubernetes CRD](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#customresourcedefinitions) introduced by Kubeflow that wraps a Kubernete
Also, this should flow into the next paragraph like the current website does, e.g. there should not be a new line here.

2025-02-02 04:29 UTC, terrytangyuan reviewed
I am not sure about these changes. I feel like most of these linked concepts (namespace, configmap, CRD, etc.) should be prerequisites before reading or learning about Kubeflow

2025-02-07 17:54 UTC, varodrig commented
> I am not sure about these changes. I feel like most of these linked concepts (namespace, configmap, CRD, etc.) should be prerequisites before reading or learning about Kubeflow

Do you think adding a link to the technical documentation will not help the reader? I agree that people should probably know already about it, but what if you do not remember a specific concept at that time. 
Do you think we should assume that all our audience are knowledge about CRDs and other kubernetes concepts?

2025-02-11 14:18 UTC, hbelmiro commented
Testing resolves for an issue from a different repo.

Fixes: https://github.com/kubeflow/pipelines/issues/11612

2025-02-11 14:19 UTC, hbelmiro commented
Fixes: https://github.com/kubeflow/pipelines/issues/11612

2025-02-11 20:18 UTC, terrytangyuan commented
No preference here

2025-02-14 02:53 UTC, varodrig commented
@thesuperzapper  any news on this? Are they are changes needed?

Thanks.

2025-02-14 17:17 UTC, andreyvelich commented
/assign @terrytangyuan @kubeflow/wg-manifests-leads @thesuperzapper Please review when you have time.

2025-02-14 17:43 UTC, thesuperzapper requested changes

2025-02-14 17:43 UTC, thesuperzapper commented on content/en/docs/components/central-dash/profiles.md
> +
Can we keep this as a single paragraph, It's a bit short otherwise. 

That is, can we remove these new lines.

2025-02-14 17:44 UTC, thesuperzapper commented
/retitle Small updates to Central Dashboard docs

2025-02-18 05:52 UTC, varodrig commented on content/en/docs/components/central-dash/profiles.md
> +
![image](https://github.com/user-attachments/assets/4181a917-927e-4d14-a7e5-689c5cddb075)

2025-02-18 13:43 UTC, varodrig commented
/assign @terrytangyuan @kubeflow/wg-manifests-leads @thesuperzapper Please review when you have time.
PR ready

2025-02-18 15:15 UTC, juliusvonkohout commented on content/en/docs/components/central-dash/profiles.md
> +A Kubeflow Profile is a [Kubernetes CRD](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#customresourcedefinitions) introduced by Kubeflow that wraps a Kubernete
ProfileS are owned by a single user,

2025-02-18 15:17 UTC, juliusvonkohout commented
/lgtm

are there any strong objections? Because otherwise I would approve it as well.

2025-02-20 17:59 UTC, thesuperzapper commented on content/en/docs/components/central-dash/profiles.md
> +A Kubeflow Profile is a [Kubernetes CRD](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#customresourcedefinitions) introduced by Kubeflow that wraps a Kubernete
I push a fix to the branch for this

2025-02-20 18:01 UTC, thesuperzapper commented
I pushed a commit to the branch to fix the typo of "Profile" when it should have been "profiles" (not from your PR, but was already there in the website).

It's fine to mere now.

/lgtm
/approve

2025-02-20 18:04 UTC, merged